### ISSUE TITLE
Using Docker as standard Strapi won't upload

### ISSUE THREAD

**Issue by gkurl** [viktorfa/strapi-4-serverless-guide#2]
Hey Vik,

I've got Serverless working with Dockerfile containers to bypass the 250mb limit.

Docker image is building fine and uploading to serverless.

Dockerimage:

```
FROM amazon/aws-lambda-nodejs:16
WORKDIR /var/task
RUN npm i python3
COPY src /var/task
COPY build /var/task
COPY config /var/task
COPY database /var/task
COPY public /var/task
COPY package*.json /var/task
COPY .env.example /var/task
RUN npm install
RUN chmod -R 777 /var/task
CMD [ "app.strapiHandler" ]
```

But when I deploy to Serverless the logs show this:

```
INFO	Cold starting Strapi
/bin/sh: hostname: command not found
[2022-10-03 17:34:10.375] debug: ⛔️ Server wasn't able to start properly.
[2022-10-03 17:34:10.377] error: The public folder (/var/task/public) doesn't exist or is not accessible. Please make sure it exists.
Error: The public folder (/var/task/public) doesn't exist or is not accessible. Please make sure it exists.
at module.exports (/var/task/node_modules/@strapi/strapi/lib/core/bootstrap.js:29:11)
at async Strapi.register (/var/task/node_modules/@strapi/strapi/lib/Strapi.js:380:5)
at async Strapi.load (/var/task/node_modules/@strapi/strapi/lib/Strapi.js:474:5)
at async startStrapi (/var/task/app.js:16:7)
at async Runtime.module.exports.strapiHandler [as handler] (/var/task/app.js:36:5)
```

I've tried as much as I can to try and figure out why it can't detect the public directory. Any help would be appreciated at this point as I think I've hit a wall.

**Comment by lzygmanski** [comment]
I have the same problem, any news?

**Comment by gkurl** [comment]
> I have the same problem, any news?

Hey yes, I figured out the correct Dockerfile config in the end:

```
FROM amazon/aws-lambda-nodejs:16
WORKDIR /var/task
RUN npm i python3
COPY src /var/task/src
COPY build /var/task/build
COPY config /var/task/config
COPY database /var/task/database
COPY public /var/task/public
COPY package*.json /var/task
COPY .env.example /var/task
RUN npm install
RUN npm install --platform=linux --arch=x64 sharp
RUN chmod -R 755 /var/task
CMD [ "/var/task/src/app.strapiHandler" ]
```

Explicit directory definitions and some npm install commands got it running.

**Comment by vikramdewangan** [comment]
Hi @gkurl, can you share the serverless.yml configuration for the Docker thanks.
